### ISSUE TITLE
generation failed

### ISSUE THREAD

**Issue by zyh-uaiaaaa** [Godheritage/BOTH2Hands#3]
Hi, 

I want to run the generation file to generate a motion for a given text, but it shows that the dataset of "proceed_data_str = "bodyhand_processed_dataset_"  meanstd_str = "bodyhand_processed_dataset_meanstd_"" does not exist, what should I do? Plus, the given dataset preparation link is 404.

thanks,

**Comment by Godheritage** [comment]
Thank you for your reply. We have fixed the README and dataset scripts, and the generation should now work properly. However, we highly recommend that you apply for our dataset first, as the mean and std will be affected by the number of motions.
