### ISSUE TITLE
您好，恳求解决一下python main.py --config gen.yaml动作生成的bug以及动作生成结果不够准确的问题

### ISSUE THREAD

**Issue by Michae1mzm** [Godheritage/BOTH2Hands#4]
在完成环境配置和下载checkpoint后，我使用示例数据集进行动作生成，但遇到了以下错误：
![1](https://github.com/user-attachments/assets/b22db2e9-4c05-444e-be83-9753fd5b2d59)
![2](https://github.com/user-attachments/assets/9085d48d-7255-4676-925f-379f598f15ab)
我怀疑是由于noise_t_embed和cond_embed在批量大小（batch size）上未对齐所致。3

为了解决这个问题，我尝试了以下方法：
1.使用 cond_embed[:10] 进行相加：
将embed = noise_t_embed + cond_embed改为embed = noise_t_embed + cond_embed[:10]
![3](https://github.com/user-attachments/assets/3752ecd5-1232-4cc1-a3e7-9064ce335d69)
2.使用下面注释的内容：（图四）
#embed = noise_t_embed + cond_embed
embed = noise_t_embed
![4](https://github.com/user-attachments/assets/72d8ca93-b2df-4ec8-986a-2daf7b322641)
这两种方法都能在checkpoints/example_gen/vis_res/style/1生成输出，终端输出为：(图五)
![5](https://github.com/user-attachments/assets/f5a189f6-a7fb-4ded-a709-7ad1806e73d2)
然而，在Unity中可视化输出结果时，效果不理想。
恳请学长在百忙之中给予指导，如何解决上述错误，并使生成的动作结果与展示效果相同，非常感谢！！

**Comment by Godheritage** [comment]
generation problem fixed

**Comment by xinyuzhang915** [comment]
@Michae1mzm 请问你最后动作生成的结果在Unity中展示出来的效果好吗？
